### ISSUE TITLE
Misleading comment: 2^12 != 2048

### ISSUE THREAD

**Issue by neokril** [NordicSemiconductor/nRF52-ADC-examples#4]
My calculator shows that 2^12 = 4096, not 2048 as written in your source code. 

https://github.com/NordicSemiconductor/nRF52-ADC-examples/blob/b4fbd256c886e07a515a8570a2f3d8c01cc1e913/saadc_low_power/main.c#L211

**Comment by jorhol** [comment]
Fixed: https://github.com/NordicPlayground/nRF52-ADC-examples/commit/e7eddbd6de052aa388b30cb06075d7a507dc4c40
